### ISSUE TITLE
能不能在win10，cup复现算法呢？

### ISSUE THREAD

**Issue by gaochubushenghan** [MaybeShewill-CV/attentive-gan-derainnet#13]

**Comment by gaochubushenghan** [comment]
请问test_model(args.image_path, args.weights_path)  image_path在哪？

**Comment by MaybeShewill-CV** [comment]
@gaochubushenghan 你可以看下readme 这个是参数 需要你自己输入

**Comment by gaochubushenghan** [comment]
Traceback (most recent call last):
  File "tools/test_model.py", line 148, in <module>
    test_model(args.image_path, args.weights_path)
  File "tools/test_model.py", line 61, in test_model
    assert ops.exists(image_path)
  File "D:\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument
请问这是什么问题啊？

**Comment by gaochubushenghan** [comment]
D:\Anaconda3\attentive-gan-derainnet-master>python tools/test_model.py --weights_path model/new_model/derain_gan_2018-10-09-11-06-58.ckpt-200000
Traceback (most recent call last):
  File "tools/test_model.py", line 148, in <module>
    test_model(args.image_path, args.weights_path)
  File "tools/test_model.py", line 61, in test_model
    assert ops.exists(image_path)
  File "D:\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument
请问这个是什么问题？
