### ISSUE TITLE
关于数据集的放置问题

### ISSUE THREAD

**Issue by duguangmeiyu** [MaybeShewill-CV/attentive-gan-derainnet#3]
hello，首先感谢分享如此优秀的代码，我有一些问题想请教您一下。首先数据集我下载的是原作者提供的数据集，我在data文件夹下新建了training_data_example然后将训练图片集放了进去，请问这样操作对吗？还有我运行程序的时候报了这样的错
Traceback (most recent call last):
  File "tools/train_model.py", line 209, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "tools/train_model.py", line 58, in train_model
    train_dataset = data_provider.DataSet(ops.join(dataset_dir, 'train.txt'))
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 30, in __init__
    self._gt_img_list, self._gt_label_list = self._init_dataset(dataset_info_file)
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 43, in _init_dataset
    assert ops.exists(dataset_info_file), '{:s}　不存▒?.format(dataset_info_file)'
AssertionError: {:s}　不存▒?.format(dataset_info_file)
请问这是什么问题呢。。。新手上路很多不懂很不好意思，占用了您一些时间还望海涵，感谢！！

**Comment by MaybeShewill-CV** [comment]
@duguangmeiyu 我好像放了放置示例数据集存放格式,等我有空了整理一下放上去。==！

**Comment by duguangmeiyu** [comment]
好的好的非常感谢，那请问这个运行的报错问题您遇到过么。。。有没有什么解决的办法。。。非常感谢！！！

**Comment by MaybeShewill-CV** [comment]
@duguangmeiyu 这个运行报错就是因为你没有按照我的规则组织训练数据, 你重新pull一下代码然后看一下data里面的training example data然后按照那个例子的样子重新组织一下你的训练数据就好了

**Comment by duguangmeiyu** [comment]
非常感谢！！！然后又出现了新的报错= =！！
VGG16 Network init complete
Traceback (most recent call last):
  File "tools/train_model.py", line 209, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "tools/train_model.py", line 88, in train_model
    ssim = ssim_computer.compute_ssim(tf.image.rgb_to_grayscale(net_output),
NameError: global name 'ssim_computer' is not defined
非常抱歉占用了您宝贵的时间= =！！再次非常感谢！！！

**Comment by duguangmeiyu** [comment]
File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 130, in next_batch
    return self.next_batch(batch_size)
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 130, in next_batch
    return self.next_batch(batch_size)
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 130, in next_batch
    return self.next_batch(batch_size)
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 128, in next_batch
    self._random_dataset()
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 61, in _random_dataset
    random_idx = np.random.permutation(len(self._gt_img_list))
  File "mtrand.pyx", line 4907, in mtrand.RandomState.permutation
  File "mtrand.pyx", line 4841, in mtrand.RandomState.shuffle
RuntimeError: maximum recursion depth exceeded in cmp
非常感谢您对我问题的解答，但是又出现了新的问题，不知道您有没有遇到类似的情况，有没有什么好的解决方法= =！！占用了您的宝贵时间还望您海涵！！！再次非常感谢！！！

**Comment by duguangmeiyu** [comment]
非常感谢您对我问题的解答，但是我又遇到了新的问题= =！
 File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 130, in next_batch
    return self.next_batch(batch_size)
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 130, in next_batch
    return self.next_batch(batch_size)
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 128, in next_batch
    self._random_dataset()
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 61, in _random_dataset
    random_idx = np.random.permutation(len(self._gt_img_list))
  File "mtrand.pyx", line 4907, in mtrand.RandomState.permutation
  File "mtrand.pyx", line 4841, in mtrand.RandomState.shuffle
RuntimeError: maximum recursion depth exceeded in cmp
不知道您有没有对这个问题的应对方法，再次非常感谢！！

**Comment by MaybeShewill-CV** [comment]
@duguangmeiyu 可以截图你的训练数据集文件夹 和你的train.txt文件

**Comment by duguangmeiyu** [comment]
额。。。。这个问题解决了。。。然后又出现问题了。。。我自己都尴尬了。。。谢谢大佬！！
VGG16 Network init complete
2018-09-18 08:27:01.787846: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
I0918 08:27:02.986565 17810 train_model.py:136] Global configuration is as follows:
I0918 08:27:02.999047 17810 train_model.py:137] {'TEST': {'TF_ALLOW_GROWTH': True, 'IMG_HEIGHT': 240, 'BATCH_SIZE': 1, 'GPU_MEMORY_FRACTION': 0.8, 'IMG_WIDTH': 360}, 'TRAIN': {'LEARNING_RATE': 0.002, 'IMG_WIDTH': 360, 'BATCH_SIZE': 1, 'EPOCHS': 200010, 'IMG_HEIGHT': 240, 'TF_ALLOW_GROWTH': True, 'GPU_MEMORY_FRACTION': 0.95}}
I0918 08:27:06.023253 17810 train_model.py:145] Training from scratch
Traceback (most recent call last):
  File "tools/train_model.py", line 212, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "tools/train_model.py", line 170, in train_model
    gt_imgs, label_imgs, mask_imgs = train_dataset.next_batch(CFG.TRAIN.BATCH_SIZE)
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/data_provider.py", line 143, in next_batch
    gt_image = cv2.resize(gt_image, (CFG.TRAIN.IMG_WIDTH, CFG.TRAIN.IMG_HEIGHT))
cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by MaybeShewill-CV** [comment]
@duguangmeiyu 你的脚本执行目录应该是在attentive-gan-derainnet-master这一级目录下 所以你的数据路径相对路径应该是从data开始。为了避免错误建议直接写绝对路径.

**Comment by duguangmeiyu** [comment]
通了通了！！！谢谢大佬！！！！爱你！！！！1

**Comment by MaybeShewill-CV** [comment]
@duguangmeiyu 不客气

**Comment by MaybeShewill-CV** [comment]
Since no further question about it I will close it

**Comment by liulng** [comment]
@duguangmeiyu 请问你数据集在哪找的呀，能不能发个链接或者加我qq1129620314发我，感谢

**Comment by xuchen-dev** [comment]
> @duguangmeiyu 请问你数据集在哪找的呀，能不能发个链接或者加我qq1129620314发我，感谢

同求
