### ISSUE TITLE
运行代码报错

### ISSUE THREAD

**Issue by duguangmeiyu** [MaybeShewill-CV/attentive-gan-derainnet#56]
Traceback (most recent call last):
  File "train_model.py", line 20, in <module>
    import derain_drop_net
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/derain_drop_net.py", line 13, in <module>
    import attentive_gan_net
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/attentive_gan_net.py", line 13, in <module>
    import cnn_basenet
  File "/home/liuguangyu/attentive-gan-derainnet-master/tools/cnn_basenet.py", line 12, in <module>
    import tensorflow.contrib.layers as tf_layer
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 33, in <module>
    from tensorflow.contrib import autograph
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/contrib/autograph/__init__.py", line 24, in <module>
    from tensorflow.python.autograph import *  # pylint:disable=wildcard-import
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/autograph/__init__.py", line 25, in <module>
    from tensorflow.python.autograph import operators
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/autograph/operators/__init__.py", line 40, in <module>
    from tensorflow.python.autograph.operators.control_flow import for_stmt
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 21, in <module>
    from tensorflow.python.autograph.operators import py_builtins
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/autograph/operators/py_builtins.py", line 26, in <module>
    from tensorflow.python.autograph.utils import py_func
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/autograph/utils/__init__.py", line 25, in <module>
    from tensorflow.python.autograph.utils.tensor_list import dynamic_list_append
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/autograph/utils/tensor_list.py", line 22, in <module>
    from tensorflow.python.ops import list_ops
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/ops/list_ops.py", line 32, in <module>
    ops.NotDifferentiable("TensorListConcat")
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2447, in NotDifferentiable
    _gradient_registry.register(None, op_type)
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/traceback.py", line 358, in extract
    f.line
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/traceback.py", line 282, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/liuguangyu/anaconda3/envs/tf2/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1092-1093: invalid continuation byte
您好请问这个问题是什么情况啊= =！！！

**Comment by MaybeShewill-CV** [comment]
@duguangmeiyu 应该是运行环境不一样导致的吧 这个不是模型问题 是和python有关系的问题 建议查stackoverflow或者csdn:)
