### ISSUE TITLE
How do we train the GAN

### ISSUE THREAD

**Issue by zhaojianghe16** [MaybeShewill-CV/attentive-gan-derainnet#6]
Dear friend,
      I was following your instructions of training the network. However, there's a traceback.

Traceback (most recent call last):
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 212, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 154, in train_model
    encoding='latin1').item()
  File "D:\Anaconda3333\lib\site-packages\numpy\lib\npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/vgg16.npy'

Could you please clarify this "vgg16.npy"? 

Best

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 vgg16.npy is the pretrained vgg16 network weights based on the imagenet dataset. Since it is too big to push to the repo so you can google the file by yourself and download it into ./data folder.

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV 
     谢谢您的回复，我下载了vgg16然后尝试training。 但是我发现即使我用了绝对路径（下面粗体字）
     但是图片好像没有被成功读取。请问这个可能是什么原因呢？（training dataset是下载就在这个project文件夹里面的，没有做过更改）我可以手动打开图片 例如0_rain.png. 我也检查了train.txt 都和github上面的train.txt是一样的。 希望能学习到解决的方法，谢谢~

     D:\Anaconda3\python.exe D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py --dataset_dir **D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/ --weights_path D:/gitGAN/attentive-gan-derainnet-master/model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000**
VGG16 Network init complete
2018-10-07 12:53:01.952514: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-10-07 12:53:03.086311: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2018-10-07 12:53:03.086744: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2018-10-07 12:53:03.961881: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-07 12:53:03.962154: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0 
2018-10-07 12:53:03.962345: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N 
2018-10-07 12:53:03.962667: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3891 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
I1007 12:53:14.013186 12860 train_model.py:135] Global configuration is as follows:
I1007 12:53:14.013186 12860 train_model.py:136] {'TRAIN': {'EPOCHS': 200010, 'LEARNING_RATE': 0.002, 'GPU_MEMORY_FRACTION': 0.95, 'TF_ALLOW_GROWTH': True, 'BATCH_SIZE': 1, 'IMG_HEIGHT': 240, 'IMG_WIDTH': 360}, 'TEST': {'GPU_MEMORY_FRACTION': 0.8, 'TF_ALLOW_GROWTH': True, 'BATCH_SIZE': 1, 'IMG_HEIGHT': 240, 'IMG_WIDTH': 360}}
I1007 12:53:18.744264 12860 train_model.py:148] Restore model from last model checkpoint D:/gitGAN/attentive-gan-derainnet-master/model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000
INFO:tensorflow:Restoring parameters from D:/gitGAN/attentive-gan-derainnet-master/model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000
I1007 12:53:18.744264 12860 tf_logging.py:115] Restoring parameters from D:/gitGAN/attentive-gan-derainnet-master/model/derain_gan_v2_2018-07-23-11-26-23.ckpt-200000
**OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp, line 4044**
**Traceback (most recent call last):**
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 212, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 170, in train_model
    gt_imgs, label_imgs, mask_imgs = train_dataset.next_batch(CFG.TRAIN.BATCH_SIZE)
  File "D:\gitGAN\attentive-gan-derainnet-master\data_provider\data_provider.py", line 144, in next_batch
    gt_image = cv2.resize(gt_image, (CFG.TRAIN.IMG_WIDTH, CFG.TRAIN.IMG_HEIGHT))
**cv2.error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize**


Process finished with exit code 1

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 你可以检查train.txt文件 里面使用绝对路径记录图像路径

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV  
谢谢你的回复。 我检查了train.txt 也加上了绝对路径。我发现你的train.txt最后一行好像有个小问题（/data/**training_data_examplen**/gt_label/3_clean.png /data/training_data_example/data/3_rain.png）这里example多了一个n，你可以看到路径长度没有全部对齐.

如果train.txt是下面这样（每一行只是定义一个路径（轮流定义#_clean.png 和 #_rain.png））
![image](https://user-images.githubusercontent.com/38481194/46591527-3c342b80-ca70-11e8-92fa-d0c12e6e5a5d.png)
Pycharm output 是 
Traceback (most recent call last):
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 212, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 59, in train_model
    train_dataset = data_provider.DataSet(ops.join(dataset_dir, 'train.txt'))
  File "D:\gitGAN\attentive-gan-derainnet-master\data_provider\data_provider.py", line 31, in __init__
    self._gt_img_list, self._gt_label_list = self._init_dataset(dataset_info_file)
  File "D:\gitGAN\attentive-gan-derainnet-master\data_provider\data_provider.py", line 50, in _init_dataset
    **gt_img_list.append(info_tmp[1])
IndexError: list index out of range**


**如果train.txt是（每一行定义一对训练图片）：**
D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/data/training_data_example/gt_label/0_clean.png D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/data/training_data_example/data/0_rain.png
D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/data/training_data_example/gt_label/1_clean.png D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/data/training_data_example/data/1_rain.png
D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/data/training_data_example/gt_label/2_clean.png D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/data/training_data_example/data/2_rain.png
D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/data/training_data_example/gt_label/3_clean.png D:/gitGAN/attentive-gan-derainnet-master/data/training_data_example/data/training_data_example/data/3_rain.png
（每一行定义了 clean.png 和 #_rain.png）

pycharm output：
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 212, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 170, in train_model
    gt_imgs, label_imgs, mask_imgs = train_dataset.next_batch(CFG.TRAIN.BATCH_SIZE)
  File "D:\gitGAN\attentive-gan-derainnet-master\data_provider\data_provider.py", line 144, in next_batch
    gt_image = cv2.resize(gt_image, (CFG.TRAIN.IMG_WIDTH, CFG.TRAIN.IMG_HEIGHT))
**cv2.error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize**

请问我是应该用第一种吗？但是那个error应该怎么解决呢？ 
谢谢~

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 每一行对应一对训练样本 两个图像路径之间使用空格分隔就可以了 具体你可以看一下dataprovider相关的代码就知道了。

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV 
谢谢你的回复。现在的路径是正确了的。非常感动！！！
代码说我的**RAN OUT OF MEMORY**
请问我在**资源有限**的情况下 **修改什么能继续高效的training**呢？
我的笔记本显卡是GTX 1050Ti （显存4G）还有HD graphic 630。
我的专用内存有4G 共享内存4G（请问可以调用共享内存的吗？可以CPU,GPU0,GPU1全部一起的吗？）
我尝试过把tf.device改成在CPU上进行，但是这样跑起来太慢了。
我尝试过修改input图片大小，但是这样tensor的dimension会报错（感觉有迷茫）

请问有哪方面我修改过后可以继续training的呢？  希望大神可以抽空指点迷津谢谢你~

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 4G显存太小了 这样你只能改小网络的输入数据大小，修改config/global_config.py里面的参数设置。

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV 感谢秒回哈哈.
你说的很对，我之前看过global_config.py。可是这里可以调整的参数我都尝试过了。 **__C.TRAIN.GPU_MEMORY_FRACTION这个我改成了1（最大限度的使用）**
__C.TRAIN.BATCH_SIZE（这个已经是最小了）
**__C.TRAIN.IMG_HEIGHT 和 __C.TRAIN.IMG_WIDTH 我都缩小了10倍。然后就报错了...**
**请问还有有什么可以修改的吗？谢谢**


我可以test 这个没有任何问题
# Train options
__C.TRAIN = edict()

# Set the shadownet training epochs
__C.TRAIN.EPOCHS = 200010
# Set the initial learning rate
__C.TRAIN.LEARNING_RATE = 0.002
# Set the GPU resource used during training process
__C.TRAIN.GPU_MEMORY_FRACTION =1     #0.95
# Set the GPU allow growth parameter during tensorflow training process
__C.TRAIN.TF_ALLOW_GROWTH = True
# Set the shadownet training batch size
__C.TRAIN.BATCH_SIZE = 1
# Set train image height
**__C.TRAIN.IMG_HEIGHT = 24 #240
# Set train image width
__C.TRAIN.IMG_WIDTH = 36 #360**

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 麻烦贴一下错误截图

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV 不好意思上次的评论github自动调了字体粗体大小。下面的错误是因为我在config更改了（Height，width都缩小了10倍）
**__C.TRAIN.IMG_HEIGHT = 24
__C.TRAIN.IMG_WIDTH = 36**  请问解决这个traceback复杂吗？ 谢谢~
Traceback (most recent call last):
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [32,1024] rhs shape= [768,1024]
	 [[Node: save/Assign_457 = Assign[T=DT_FLOAT, _class=["loc:@derain_net_loss/discriminative_loss/discriminative_inference/fc_1/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](derain_net_loss/discriminative_loss/discriminative_inference/fc_1/kernel/Adam_1, save/RestoreV2:457)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 212, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 149, in train_model
    saver.restore(sess=sess, save_path=weights_path)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\training\saver.py", line 1752, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [32,1024] rhs shape= [768,1024]
	 [[Node: save/Assign_457 = Assign[T=DT_FLOAT, _class=["loc:@derain_net_loss/discriminative_loss/discriminative_inference/fc_1/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](derain_net_loss/discriminative_loss/discriminative_inference/fc_1/kernel/Adam_1, save/RestoreV2:457)]]

Caused by op 'save/Assign_457', defined at:
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 212, in <module>
    train_model(args.dataset_dir, weights_path=args.weights_path)
  File "D:/gitGAN/attentive-gan-derainnet-master/tools/train_model.py", line 102, in train_model
    saver = tf.train.Saver()
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\training\saver.py", line 1284, in __init__
    self.build()
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\training\saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\training\saver.py", line 1333, in _build
    build_save=build_save, build_restore=build_restore)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\training\saver.py", line 781, in _build_internal
    restore_sequentially, reshape)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\training\saver.py", line 422, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\training\saver.py", line 113, in restore
    self.op.get_shape().is_fully_defined())
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\ops\state_ops.py", line 219, in assign
    validate_shape=validate_shape)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 59, in assign
    use_locking=use_locking, name=name)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "D:\Anaconda3333\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [32,1024] rhs shape= [768,1024]
	 [[Node: save/Assign_457 = Assign[T=DT_FLOAT, _class=["loc:@derain_net_loss/discriminative_loss/discriminative_inference/fc_1/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](derain_net_loss/discriminative_loss/discriminative_inference/fc_1/kernel/Adam_1, save/RestoreV2:457)]]


Process finished with exit code 1

**Comment by zhaojianghe16** [comment]
@MaybeShewill-CV  
Oh my god大兄弟!!!! 成功了 
开始training了 非常谢谢你！！
（我将patch size改成了64， height 120 and width 180）

**Comment by MaybeShewill-CV** [comment]
@zhaojianghe16 嗯 patch_size对你没什么用 那是我在另外一个项目里面用的 push上来的时候忘了删除了==！ 你就只需要改图像输入尺寸就可以了。
