### ISSUE TITLE
关于train_model.py文件无法正常运行

### ISSUE THREAD

**Issue by AlanLouis12** [MaybeShewill-CV/attentive-gan-derainnet#96]
运行train_model.py文件的时候，总会报错如下：
Traceback (most recent call last):
  File "D:\anaconda3\envs\abcd\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "D:\anaconda3\envs\abcd\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "D:\anaconda3\envs\abcd\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[{{node val_IteratorGetNext}}]]
尝试了很多方法都无法解决，请问你可以帮我解答一下吗，谢谢

**Comment by MaybeShewill-CV** [comment]
@AlanLouis12 你的dataloader没有正常的加载到数据:)
